name: hasura_cache_interceptor
description: Package to implements cache in Hasura package
version: 1.0.0-dev.8

issue_tracker: https://github.com/Flutterando/hasura_connect/issues
repository: https://github.com/Flutterando/hasura_connect/tree/master/packages/hasura_cache_interceptor
homepage: https://github.com/Flutterando/hasura_connect/tree/master/packages/hasura_cache_interceptor
documentation: https://github.com/Flutterando/hasura_connect/blob/master/packages/hasura_cache_interceptor/README.md

environment:
  sdk: ">=2.16.0 <4.0.0"

dependencies:
  # hasura_connect: ^5.0.1
  http: ^1.2.1
  uuid: ^4.4.0

dependency_overrides: 
  hasura_connect: 
    path: ../hasura_connect

dev_dependencies:
  lint: ^2.3.0
  mocktail: ^1.0.4
  test: ^1.25.7
  
  flutterando_analysis: 
    git: https://github.com/Flutterando/flutterando_analysis.git
