name: hasura_cache_interceptor
description: Package to implements cache in Hasura package
version: 1.0.0-dev.7

issue_tracker: https://github.com/Flutterando/hasura_connect/issues
repository: https://github.com/Flutterando/hasura_connect/tree/master/packages/hasura_cache_interceptor
homepage: https://github.com/Flutterando/hasura_connect/tree/master/packages/hasura_cache_interceptor
documentation: https://github.com/Flutterando/hasura_connect/blob/master/packages/hasura_cache_interceptor/README.md

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  hasura_connect: ^4.0.0+3
  http: ^0.13.4
  uuid: ^3.0.6

# dependency_overrides: 
#   hasura_connect: 
#     path: ../hasura_connect

dev_dependencies:
  lint: ^1.0.0
  mocktail: ^0.3.0 
  test: ^1.20.1
