name: hasura_cache_interceptor
description: Package to implements cache in Hasura package
version: 1.0.0-dev.7

homepage: https://flutterando.com.br
repository: https://github.com/Flutterando/hasura_cache_interceptor

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  uuid: ^3.0.6
  hasura_connect: ^4.0.0+2
  http: ^0.13.0

# dependency_overrides: 
#   hasura_connect: 
#     path: ../hasura_connect

dev_dependencies:
  mocktail: ^0.3.0 
  test: ^1.20.1
