name: hive_cache_interceptor
description: Package to implements cache using hive in hasura_connect package
version: 1.0.0-dev.4

issue_tracker: https://github.com/Flutterando/hasura_connect/issues
repository: https://github.com/Flutterando/hasura_connect/tree/master/packages/hive_cache_interceptor
homepage: https://github.com/Flutterando/hasura_connect/tree/master/packages/hive_cache_interceptor
documentation: https://github.com/Flutterando/hasura_connect/blob/master/packages/hive_cache_interceptor/README.md

environment:
  sdk: ">=2.16.0 <4.0.0"  

dependencies:
  flutter:
    sdk: flutter
  hasura_cache_interceptor: ">=1.0.0-dev.5 <2.0.0"
  hive: ^2.2.3
  path_provider: ^2.1.3
  platform: ^3.1.5 

dependency_overrides: 
  hasura_cache_interceptor: 
    path: ../hasura_cache_interceptor

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^2.3.0
  mocktail: ^1.0.4
  flutterando_analysis: 
    git: https://github.com/Flutterando/flutterando_analysis.git

flutter:
